In [1]:
array= ([1,2,3], [4,5,6], [7,8,9])

In [2]:
array

([1, 2, 3], [4, 5, 6], [7, 8, 9])

In [4]:
#Creacion de dataframes
import pandas as pd
df = pd.DataFrame(array)

In [5]:
df

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [9]:
#Modificacion de columnas de DataFrames
df = pd.DataFrame(data=array, index=['A', 'B', 'C'], columns= ['D', 'E', 'F'])
df

   D  E  F
A  1  2  3
B  4  5  6
C  7  8  9

In [10]:
#Sección superior
df.head(2)

   D  E  F
A  1  2  3
B  4  5  6

In [11]:
#Información de cada columna
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, A to C
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   D       3 non-null      int64
 1   E       3 non-null      int64
 2   F       3 non-null      int64
dtypes: int64(3)
memory usage: 96.0+ bytes

In [12]:
#Dimension del dataframe
df.shape

(3, 3)

In [13]:
#Cálculo de estadísticas generales de la tabla
df.describe()

         D    E    F
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [15]:
#Nombre de las columnas
df.columns

Index(['D', 'E', 'F'], dtype='object')

In [16]:
#Nombre de los renglones
df.index

Index(['A', 'B', 'C'], dtype='object')

In [19]:
#Agregar un nuevo renglón en el dataframe
df.loc['G'] = [17, 18, 19]
df

    D   E   F
A   1   2   3
B   4   5   6
C   7   8   9
G  17  18  19

In [20]:
#Extracción de columbas del dataframe
df["H"] = [17,18,19,20]
df

    D   E   F   H
A   1   2   3  17
B   4   5   6  18
C   7   8   9  19
G  17  18  19  20

In [21]:
df2 = df[["H", "I"]]
df2

KeyError: "['I'] not in index"

In [23]:
import pandas as pd
import numpy as np
arregloperros = np.array([['Comandante Pipo', 'Terry Mix', 'negro', 45, 14, '6 de mayo'],
        ['Chipote', 'Pastor tobillero con ratonero chihuahua y pug', 'negro', 35, 9, '31 de octubre'],
        ['Lenteja', 'Mestizo', 'negro', 35, 10, '5 de noviembre']])
arregloperros

array([['Comandante Pipo', 'Terry Mix', 'negro', '45', '14', '6 de mayo'],
       ['Chipote', 'Pastor tobillero con ratonero chihuahua y pug',
        'negro', '35', '9', '31 de octubre'],
       ['Lenteja', 'Mestizo', 'negro', '35', '10', '5 de noviembre']],
      dtype='<U45')

In [24]:
df = pd.DataFrame(data =arregloperros, columns= ['Nombre', 'Raza', 'Color', 'Estatura hasta la cruz', 'Peso', 'Cumpleaños'])
df

,Nombre,Raza,Color,Estatura hasta la cruz,Peso,Cumpleaños
0,Comandante Pipo,Terry Mix,negro,45,14,6 de mayo
1,Chipote,Pastor tobillero con ratonero chihuahua y pug,negro,35,9,31 de octubre
2,Lenteja,Mestizo,negro,35,10,5 de noviembre

In [26]:
df['Estatura hasta la cruz'] = df['Estatura hasta la cruz'].astype(int)

In [27]:
df[df['Estatura hasta la cruz']<50]

,Nombre,Raza,Color,Estatura hasta la cruz,Peso,Cumpleaños
0,Comandante Pipo,Terry Mix,negro,45,14,6 de mayo
1,Chipote,Pastor tobillero con ratonero chihuahua y pug,negro,35,9,31 de octubre
2,Lenteja,Mestizo,negro,35,10,5 de noviembre

In [28]:
df['Peso'] = df['Peso'].astype(int)

In [29]:
df['IMM'] = df['Peso']/(df['Estatura hasta la cruz']/100)**2
df

,Nombre,Raza,Color,Estatura hasta la cruz,Peso,Cumpleaños,IMM
0,Comandante Pipo,Terry Mix,negro,45,14,6 de mayo,69.135802
1,Chipote,Pastor tobillero con ratonero chihuahua y pug,negro,35,9,31 de octubre,73.469388
2,Lenteja,Mestizo,negro,35,10,5 de noviembre,81.632653